-- Migration file for adding direct messages
create table public.direct_messages (
  id            bigint generated by default as identity primary key,
  inserted_at   timestamp with time zone default timezone('utc'::text, now()) not null,
  message       text,
  sender_id     uuid references public.users not null,
  receiver_id   uuid references public.users not null
);
comment on table public.direct_messages is 'Private messages between two users.';

-- Enable RLS
alter table public.direct_messages enable row level security;

-- Allow users to read conversations they're part of
create policy "Allow users to read their conversations" on public.direct_messages 
  for select using (
    auth.uid() = sender_id 
    or auth.uid() = receiver_id
  );

-- Allow users to send messages
create policy "Allow users to send messages" on public.direct_messages
  for insert with check (
    auth.uid() = sender_id
  );

-- Allow users to update their own messages
create policy "Allow users to update their messages" on public.direct_messages
  for update using (
    auth.uid() = sender_id
  );

-- Allow users to delete their own messages
create policy "Allow users to delete their messages" on public.direct_messages
  for delete using (
    auth.uid() = sender_id
  );

-- Add to realtime subscription
alter publication supabase_realtime add table public.direct_messages;

-- Enable full replica identity for realtime events
alter table public.direct_messages replica identity full;